# Generated by Django 3.1.4 on 2021-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRecRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_uuid', models.CharField(max_length=100, verbose_name='UUID of record')),
                ('rec_type', models.CharField(max_length=200, verbose_name='Record type')),
                ('user_id', models.CharField(max_length=100, verbose_name='uid of user')),
                ('room_id', models.CharField(max_length=100, verbose_name='roomId of user')),
                ('user_name', models.CharField(max_length=512, verbose_name='User name')),
                ('live_title', models.CharField(max_length=2048, verbose_name='Live title')),
                ('start_date', models.DateTimeField(verbose_name='Live start time')),
                ('end_date', models.DateTimeField(verbose_name='Live end time')),
                ('rec_extra_data', models.CharField(max_length=16384, verbose_name='Extra data of this record')),
                ('contributor_info', models.CharField(max_length=2048, verbose_name='Contributor information')),
            ],
        ),
    ]
