# Generated by Django 3.1.4 on 2021-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_auto_20210102_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverecrecord',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Live end time'),
        ),
    ]
